name:                 kbc-haskell
version:              0.1.0.0
visibility:           public
id:                   kbc-haskell-0.1.0.0-inplace
key:                  kbc-haskell-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
import-dirs:
    /Users/lingyin/kbc-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/kbc-haskell-0.1.0.0/build

library-dirs:
    /Users/lingyin/kbc-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/kbc-haskell-0.1.0.0/build

library-dirs-static:
    /Users/lingyin/kbc-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/kbc-haskell-0.1.0.0/build

dynamic-library-dirs:
    /Users/lingyin/kbc-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/kbc-haskell-0.1.0.0/build

data-dir:             /Users/lingyin/kbc-haskell/.
hs-libraries:         HSkbc-haskell-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /Users/lingyin/kbc-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/kbc-haskell-0.1.0.0/doc/html/kbc-haskell/kbc-haskell.haddock

haddock-html:
    /Users/lingyin/kbc-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/kbc-haskell-0.1.0.0/doc/html/kbc-haskell
